### ISSUE TITLE
CSDA10F URDF - technical drawings 

### ISSUE THREAD

**Issue by amrith1007** [ros-industrial/motoman_experimental#10]
Hello, 
I am currently working on the URDF for the CSDA10F. I am working on converting the stp files provided by Yasakawa to STL and trying to fit them in the URDF of the SDA10F. I am unable to find any technical drawing of the CSDA10F giving me detailed information of the position of the joints. I have also contacted motomantechsupport and haven't received any reply for a while. Can someone help me verify if the joint positions of the CSDA10F are similar to that of the SDA10F

**Comment by gavanderhoorn** [comment]
> I have also contacted motomantechsupport and haven't received any reply for a while

@ted-miller, is this something you could expedite perhaps?

**Comment by ted-miller** [comment]
I'm told that a tech support representative will be reaching out this morning.

**Comment by ted-miller** [comment]
Also, it appears that you can download the technical drawings of the CSDA10F directly from Yaskawa Europe's website.
http://www.motoman.co.uk/en/products/robots/product-view/?tx_catalogrobot_pi1%5Buid%5D=3037&cHash=c42efbce73dd11be3ee17913ec63d2fa 
Please see the download links on the right.

**Comment by amrith1007** [comment]
Thank you. Although I already have access to these files, I am not sure that they are sufficient enough to find the exact positions of the joints. There is however an stp assembly file of the CSDA10F that i have found in this link. I will try to extrapolate the joint positions from this using solidworks.

**Comment by amrith1007** [comment]
Hello,

I have created the new URDF for the CSDA10F using the mesh files found on the motoman website. As of now I have only made changes to the visual links and am currently using the collision meshes from the SDA10F. It would be great if someone could proof check it and if so where can i upload the new support package for the CSDA10F . Thanks in advance.

**Comment by gavanderhoorn** [comment]
@amrith1007: I don't have access to a CSDA10, but I'm willing to do a visual check of the meshes you created. You'll have to make your support package available somewhere.

Easiest would be to fork `motoman_experimental`, add your package and provide us with the location.

**Comment by amrith1007** [comment]
Here is the link to my support package, [https://github.com/amrith1007/test.git](url)
Thanks in advance.

**Comment by amrith1007** [comment]
@gavanderhoorn friendly ping :)

**Comment by gavanderhoorn** [comment]
Hi, my apologies for my delayed reply.

I'll take a look shortly. One preliminary comment: it would be good if we can verify that there are no differences between the CSDA and the SDA with respect to robot geometry other than the shapes of the links.

**Comment by amrith1007** [comment]
Thank you very much. Yes I have gone through the technical data sheet of the two robots, seems to be no change in the geometry apart from the links. As for the collision meshes, I am using that from the SDA10F and the visual links seem to fit within the envelope of the collision meshes.

**Comment by gavanderhoorn** [comment]
Just checked your package.

![rviz_screenshot_2017_01_30-15_06_56](https://cloud.githubusercontent.com/assets/4550046/22425952/caf2219a-e6fd-11e6-93b5-a2dfeaeb2b20.png)

As you can see in the screenshot, the link origins seem to be incorrect (note the off-centre position of the axis sticking out of the flange). This seems to be a problem for all joints actually, not just the flange.

> As for the collision meshes, I am using that from the SDA10F and the visual links seem to fit within the envelope of the collision meshes.

I did not create a screenshot of this, but at for least some links this is not entirely true. I would advise you to enable both the *visual* and the *collision* rendering in RViz and then alternating between the two. You should be able to spot this pretty easily.

**Comment by gavanderhoorn** [comment]
Two other issues (though relatively minor):

 - the `visual` quality meshes are each in the range of 1 to 1.5 MB: while nicely detailed, this is unnecessary, and on lower specced machines takes up quite some resources to render at decent framerates. You can use Blender with the *decimation* modifier.
 - the `stl`s have the word `solid` in the header, leading to errors like:

    ```
    The STL file 'package://motoman_csda10f_support/meshes/csda10f/visual/csda_axis_b.STL'
    is malformed. It starts with the word 'solid', indicating that it's an ASCII STL file,
    but it does not contain the word 'endsolid' so it is either a malformed ASCII STL
    file or it is actually a binary STL file. Trying to interpret it as a binary STL file instead.
    ```

**Comment by amrith1007** [comment]
. I am not sure I get that the link origins are incorrect because, I used solidworks to measure the distance between the links and the link origins were at the centre of face in each link . I found the same  with the SDA10F which I had cloned from the motoman repository .
![screenshot from 2017-01-30 15 30 26](https://cloud.githubusercontent.com/assets/13140946/22427253/ba006126-e702-11e6-8608-4efd62430246.png)

**Comment by amrith1007** [comment]
As far as the minor issues are concerned, I will look into them , I am relatively new when it comes to using modelling software and analyzing model files. I will try to get them fixed :)

**Comment by gavanderhoorn** [comment]
> I found the same with the SDA10F which I had cloned from the motoman repository .

you are right, they are like that in the current SDA10F support package. I don't own an SDA10F, but I'd be surprised if the centre of rotation is actually located there in the real robot. So if possible, please try to update the locations to where they are supposed to be (ie: ignore the SDA10F).

**Comment by amrith1007** [comment]
i am not able to understand clearly what is wrong here as I have located the link origin from the assembly file provided by motoman and those are the exact same values on my URDF.

**Comment by gavanderhoorn** [comment]
The axis sticking out of the flange (green) is actually that of the previous link, so it would seem the orientation of the frame of at least the TCP is not as it should be. Z+ of `tool0` should be sticking out of the flange.

**Comment by amrith1007** [comment]
alright ! I get it now :) I will do the needful and keep you updated. Thank you so much once again :)

**Comment by amrith1007** [comment]
@gavanderhoorn here is the updated support and moveit package for the CSDA10F, it would be great if you could proof check it. As for the updates, I have added collision meshes and also made changes in the URDF .  I have been in contact with motomantechsupport. If my packages are fine, I could order the MotoROS package and start with ROS integration on the real robot. Thank you very much for your time and support. 

Link : https://github.com/amrith1007/motoman_csda10f

**Comment by amrith1007** [comment]
friendly ping :) @gavanderhoorn
