### ISSUE TITLE
moveit for the CSDA10F

### ISSUE THREAD

**Issue by amrith1007** [ros-industrial/motoman_experimental#11]
hello,

I recently had a problem with running the move it setup assistant to generate the moveit package for the CSDA10F robot. However, I linked the support package for the CSDA10F that I had made with the moveit package of the SDA10F and also made a few changes in the SRDF. I know this is not the actual way to go about it, but the planning seems to work fine with a few warnings. I would like some feedback if this would suffice, if not how to I fix the issue ( posted [here](http://answers.ros.org/question/252843/error-launching-moveitsetup-assistant/)) with the moveit setup assistant . Thank you very much in advance.

**Comment by gavanderhoorn** [comment]
I'm not quite sure I understand what you saying.

Did the MSA crash for you with the meshes you converted?

**Comment by amrith1007** [comment]
As the MSA wasnt working, I tried to link the URDF that I made for the CSDA10F with the existing moveit package of the SDA10F just to check if the planning worked and it did. Eventhough it works fine, I am skeptical if it would cause problems when I try to use it with the real controller.

As for the problem with the MSA,I installed it from debs and had no problem whatsoever during the installation. However, it seems to crash when I try to launch it. (saying that the MSA has died) 

I hope I have articulated it right. Thank you :)

**Comment by gavanderhoorn** [comment]
Copying a MoveIt config pkg and updating it to work for another robot is not something I'd recommend.

I've just launched the MSA myself and created a config pkg for your CSDA10F model without issue. I'm also at MoveIt 0.7.6; are you running things in a VM? Can you run RViz stand-alone?

**Comment by amrith1007** [comment]
I am not running things in a VM and I am able to run RViz stand-alone.

**Comment by gavanderhoorn** [comment]
what is the output of `dpkg -l | grep moveit`?

**Comment by amrith1007** [comment]
`amrith@amrith-ThinkPad-T420:~$ dpkg -l | grep moveit
ii  ros-indigo-motoman-sia20d-moveit-config               0.3.5-0trusty-20161115-212822-0800                  amd64        An automatically generated package with all the configuration and launch files for using the motoman_sia20d with the MoveIt Motion Planning Framework
ii  ros-indigo-moveit                                     0.7.6-0trusty-20161230-113550-0800                  amd64        Meta package that contains all essential package of MoveIt!.
ii  ros-indigo-moveit-commander                           0.7.6-0trusty-20161230-110410-0800                  amd64        Python interfaces to MoveIt
ii  ros-indigo-moveit-core                                0.7.2-0trusty-20161115-190438-0800                  amd64        Core libraries used by MoveIt!
ii  ros-indigo-moveit-fake-controller-manager             0.7.6-0trusty-20161230-095035-0800                  amd64        A fake controller manager plugin for MoveIt.
ii  ros-indigo-moveit-msgs                                0.7.5-0trusty-20161115-132254-0800                  amd64        Messages, services and actions used by MoveIt
ii  ros-indigo-moveit-planners                            0.7.6-0trusty-20161230-100852-0800                  amd64        Metapacakge that installs all available planners for MoveIt
ii  ros-indigo-moveit-planners-ompl                       0.7.0-0trusty-20161115-200900-0800                  amd64        MoveIt interface to OMPL
ii  ros-indigo-moveit-plugins                             0.7.6-0trusty-20161230-095230-0800                  amd64        Metapackage for moveit plugins.
ii  ros-indigo-moveit-ros                                 0.7.6-0trusty-20161230-113434-0800                  amd64        Components of MoveIt that use ROS
ii  ros-indigo-moveit-ros-benchmarks                      0.7.6-0trusty-20161230-101738-0800                  amd64        MoveIt tools for benchmarking
ii  ros-indigo-moveit-ros-benchmarks-gui                  0.7.6-0trusty-20161230-112127-0800                  amd64        MoveIt GUI tools for benchmarking
ii  ros-indigo-moveit-ros-control-interface               0.7.6-0trusty-20161230-090924-0800                  amd64        ros_control controller manager interface for MoveIt!
ii  ros-indigo-moveit-ros-manipulation                    0.7.2-0trusty-20161115-202025-0800                  amd64        Components of MoveIt used for manipulation
ii  ros-indigo-moveit-ros-move-group                      0.7.2-0trusty-20161115-200848-0800                  amd64        The move_group node for MoveIt
ii  ros-indigo-moveit-ros-perception                      0.7.2-0trusty-20161115-192515-0800                  amd64        Components of MoveIt connecting to perception
ii  ros-indigo-moveit-ros-planning                        0.7.2-0trusty-20161115-195213-0800                  amd64        Planning components of MoveIt that use ROS
ii  ros-indigo-moveit-ros-planning-interface              0.7.2-0trusty-20161115-204858-0800                  amd64        Components of MoveIt that offer simpler interfaces to planning and execution
ii  ros-indigo-moveit-ros-robot-interaction               0.7.2-0trusty-20161115-202624-0800                  amd64        Components of MoveIt that offer interaction via interactive markers
ii  ros-indigo-moveit-ros-visualization                   0.7.2-0trusty-20161115-210325-0800                  amd64        Components of MoveIt that offer visualization
ii  ros-indigo-moveit-ros-warehouse                       0.7.2-0trusty-20161115-202647-0800                  amd64        Components of MoveIt connecting to MongoDB
ii  ros-indigo-moveit-setup-assistant                     0.7.6-0trusty-20161230-112135-0800                  amd64        Generates a configuration package that makes it easy to use MoveIt!
ii  ros-indigo-moveit-simple-controller-manager           0.7.6-0trusty-20161230-090559-0800                  amd64        A generic, simple controller manager plugin for MoveIt.
ii  ros-indigo-rqt-moveit                                 0.5.5-0trusty-20161102-172649-0700                  amd64        An rqt-based tool that assists monitoring tasks for MoveIt! motion planner developers and users.
`

**Comment by amrith1007** [comment]
```
amrith@amrith-ThinkPad-T420:~$ dpkg -l | grep moveit
ii  ros-indigo-motoman-sia20d-moveit-config               0.3.5-0trusty-20161115-212822-0800                  amd64        An automatically generated package with all the configuration and launch files for using the motoman_sia20d with the MoveIt Motion Planning Framework
ii  ros-indigo-moveit                                     0.7.6-0trusty-20161230-113550-0800                  amd64        Meta package that contains all essential package of MoveIt!.
ii  ros-indigo-moveit-commander                           0.7.6-0trusty-20161230-110410-0800                  amd64        Python interfaces to MoveIt
ii  ros-indigo-moveit-core                                0.7.2-0trusty-20161115-190438-0800                  amd64        Core libraries used by MoveIt!
ii  ros-indigo-moveit-fake-controller-manager             0.7.6-0trusty-20161230-095035-0800                  amd64        A fake controller manager plugin for MoveIt.
ii  ros-indigo-moveit-msgs                                0.7.5-0trusty-20161115-132254-0800                  amd64        Messages, services and actions used by MoveIt
ii  ros-indigo-moveit-planners                            0.7.6-0trusty-20161230-100852-0800                  amd64        Metapacakge that installs all available planners for MoveIt
ii  ros-indigo-moveit-planners-ompl                       0.7.0-0trusty-20161115-200900-0800                  amd64        MoveIt interface to OMPL
ii  ros-indigo-moveit-plugins                             0.7.6-0trusty-20161230-095230-0800                  amd64        Metapackage for moveit plugins.
ii  ros-indigo-moveit-ros                                 0.7.6-0trusty-20161230-113434-0800                  amd64        Components of MoveIt that use ROS
ii  ros-indigo-moveit-ros-benchmarks                      0.7.6-0trusty-20161230-101738-0800                  amd64        MoveIt tools for benchmarking
ii  ros-indigo-moveit-ros-benchmarks-gui                  0.7.6-0trusty-20161230-112127-0800                  amd64        MoveIt GUI tools for benchmarking
ii  ros-indigo-moveit-ros-control-interface               0.7.6-0trusty-20161230-090924-0800                  amd64        ros_control controller manager interface for MoveIt!
ii  ros-indigo-moveit-ros-manipulation                    0.7.2-0trusty-20161115-202025-0800                  amd64        Components of MoveIt used for manipulation
ii  ros-indigo-moveit-ros-move-group                      0.7.2-0trusty-20161115-200848-0800                  amd64        The move_group node for MoveIt
ii  ros-indigo-moveit-ros-perception                      0.7.2-0trusty-20161115-192515-0800                  amd64        Components of MoveIt connecting to perception
ii  ros-indigo-moveit-ros-planning                        0.7.2-0trusty-20161115-195213-0800                  amd64        Planning components of MoveIt that use ROS
ii  ros-indigo-moveit-ros-planning-interface              0.7.2-0trusty-20161115-204858-0800                  amd64        Components of MoveIt that offer simpler interfaces to planning and execution
ii  ros-indigo-moveit-ros-robot-interaction               0.7.2-0trusty-20161115-202624-0800                  amd64        Components of MoveIt that offer interaction via interactive markers
ii  ros-indigo-moveit-ros-visualization                   0.7.2-0trusty-20161115-210325-0800                  amd64        Components of MoveIt that offer visualization
ii  ros-indigo-moveit-ros-warehouse                       0.7.2-0trusty-20161115-202647-0800                  amd64        Components of MoveIt connecting to MongoDB
ii  ros-indigo-moveit-setup-assistant                     0.7.6-0trusty-20161230-112135-0800                  amd64        Generates a configuration package that makes it easy to use MoveIt!
ii  ros-indigo-moveit-simple-controller-manager           0.7.6-0trusty-20161230-090559-0800                  amd64        A generic, simple controller manager plugin for MoveIt.
ii  ros-indigo-rqt-moveit                                 0.5.5-0trusty-20161102-172649-0700                  amd64        An rqt-based tool that assists monitoring tasks for MoveIt! motion planner developers and users.
```

**Comment by gavanderhoorn** [comment]
You have an inconsistent MoveIt installation on your laptop (note the many `0.7.2` and `0.7.6` versions).

Please rectify that and try again. All `ros-indigo-moveit-*` pkgs should be at `0.7.6`.

**Comment by amrith1007** [comment]
Thank you ! I have rectified the problem and it works :)
